principal:
    resource: "@principalBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

funciones:
    resource: '@principalBundle/Controller/Helper/'
    type: annotation